---
- name: template create users smb
  hosts: smb
  become: true
  become_user: root
  pre_tasks:
    - name: create groups
      group:
        name: smb_group
        state: present

    - name: create users
      user:
        name: "{{ item }}"
        groups: users
        append: true
      with_items:
        - smb_usr1
        - smb_usr2
        - smb_urs3
  vars:
    samba_netbios_name: SAMBA_TEST
    samba_server_string: 'Welcome to the test file server'
    samba_workgroup: TESTGROUP
    
    samba_global_include: global-include.conf

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true
    samba_server_max_protocol: SMB3

    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '
    samba_map_to_guest: Never
    samba_users:
      - name: smb_usr1
        password: password
      - name: smb_usr2
        password: password
      - name: smb_usr3
        password: password
    samba_username_map:
      - from: 'User Une'
        to: smb_usr1 
#      - from: 'User Two'
#        to: smb_usr2
#      - from: 'User Three'
#        to: smb_usr3
    samba_shares_root: /srv/samba
    samba_shares:
      - name: pictures
        comment: 'Only readable/writeable by usr1'
        valid_users: smb_usr1
        write_list: smb_usr1
        group: smb_group
        browseable: 'no'
      - name: guestshare
        comment: 'Share accessible for guests'
        guest_ok: 'yes'
        writable: 'yes'
        browseable: 'yes'
  roles:
    - bertvv.samba
